# Generated by Django 4.1.5 on 2023-01-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nombre Completo'),
        ),
    ]
